{
 "title": "Nimbus Portal",
 "description": "Dashboard for Nimbus Portal client",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(portal_message_requests_incoming_total{job=\"nimbus-fluffy-metrics\"}, instance)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(portal_message_requests_incoming_total{job=\"nimbus-fluffy-metrics\", instance=\"$instance\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) * 100"
    }
   ]
  },
  {
   "title": "RSS mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "GC Mem Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nim_gc_mem_occupied_bytes{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "timeseries",
   "description": "Nimbus Portal client version and Nim version",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nimbus_portal_client_version{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "nimbus_portal_client_nim_version{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{version}}-{{nim_commit}}"
    }
   ]
  },
  {
   "title": "ENR auto updates",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discovery_enr_auto_update_total{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "uTP established connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "utp_established_connections{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "Pruning counter",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_pruning_counter_total{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "Pruning counter",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_pruning_deleted_elements{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU usage %"
    },
    {
     "expr": "process_open_fds{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(nim_gc_mem_bytes{instance=\"${instance}\",container=\"${container}\"})",
     "legendFormat": "Nim GC mem total"
    },
    {
     "expr": "sum(nim_gc_mem_occupied_bytes{instance=\"${instance}\",container=\"${container}\"})",
     "legendFormat": "Nim GC mem used"
    }
   ]
  },
  {
   "title": "Portal message requests out / responses in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(portal_message_requests_outgoing_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])"
    },
    {
     "expr": "rate(portal_message_response_incoming_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "GC heap objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "Portal message requests in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(portal_message_requests_incoming_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])"
    },
    {}
   ]
  },
  {
   "title": "Discv5 session cache hit/miss ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(discovery_session_lru_cache_hits_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) / (rate(discovery_session_lru_cache_hits_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) + rate(discovery_session_lru_cache_misses_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]))",
     "legendFormat": "session cache hits / (hits + misses)"
    },
    {
     "expr": "rate(discovery_session_decrypt_failures_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "session decrypt failures"
    }
   ]
  },
  {
   "title": "Content Requests per lookup",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_lookup_content_requests_bucket{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ENRs packed per Nodes msg",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_nodes_enrs_packed_bucket{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Content Keys Offered",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_content_keys_offered_bucket{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ENRs packed per Content msg",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_content_enrs_packed_bucket{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Discv5 message rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(discovery_message_requests_incoming_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "discovery_message_requests_incoming [{{response}}]"
    },
    {
     "expr": "rate(discovery_message_requests_outgoing_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "discovery_message_requests_outgoing [{{response}}]"
    },
    {
     "expr": "rate(discovery_unsolicited_messages_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "unsolicited messages"
    }
   ]
  },
  {
   "title": "Content Keys Accepted",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_content_keys_accepted_bucket{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Routing table nodes - BUGGED: Metrics count over all routing tables together",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "routing_table_nodes{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "Neighborhood gossip content offers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(portal_gossip_offers_successful_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "portal_gossip_offers_successful[{{protocol_id}}]"
    },
    {
     "expr": "rate(portal_gossip_offers_failed_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "portal_gossip_offers_failed[{{protocol_id}}]"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(portal_offer_accept_codes_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "portal_offer_accept_codes[protocol_id={{protocol_id}, accept_code={{accept_code}}]"
    },
    {
     "expr": "rate(portal_handle_offer_accept_codes_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "portal_handle_offer_accept_codes[protocol_id={{protocol_id}, accept_code={{accept_code}}]"
    }
   ]
  },
  {
   "title": "uTP incoming connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(utp_allowed_incoming_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "utp_allowed_incoming"
    },
    {
     "expr": "rate(utp_declined_incoming_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "utp_declined_incoming"
    }
   ]
  },
  {
   "title": "Neighborhood gossip node lookups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(portal_gossip_with_lookup_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "portal_gossip_with_lookup[{{protocol_id}}]"
    },
    {
     "expr": "rate(portal_gossip_without_lookup_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "portal_gossip_without_lookup[{{protocol_id}}]"
    },
    {
     "expr": "portal_gossip_without_lookup_total{instance=\"${instance}\",container=\"${container}\"} / (portal_gossip_without_lookup_total{instance=\"${instance}\",container=\"${container}\"} + portal_gossip_with_lookup_total{instance=\"${instance}\",container=\"${container}\"})",
     "legendFormat": "portal_gossip_lookup_ratio[{{protocol_id}}]"
    }
   ]
  },
  {
   "title": "uTP outgoing connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(utp_success_outgoing_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "utp_success_outgoing"
    },
    {
     "expr": "rate(utp_failed_outgoing_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "utp_failed_outgoing"
    }
   ]
  },
  {
   "title": "Portal message decoding failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "portal_message_decoding_failures_total{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "uTP Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(utp_failed_packets_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "utp_failed_packets"
    },
    {
     "expr": "rate(utp_received_packets_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "utp_received_packets"
    }
   ]
  },
  {
   "title": "log. distance of requested content ",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_find_content_log_distance_bucket{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "uTP established connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "utp_established_connections{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "History network pruning statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "portal_pruning_counter_total{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "Number of pruning event"
    },
    {
     "expr": "portal_pruning_deleted_elements{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "Number of elements deleted in pruning event"
    }
   ]
  },
  {
   "title": "log. distance of offered content",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_offer_log_distance_bucket{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Portal poke offers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(portal_poke_offers_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "portal_poke_offers_total[{{protocol_id}}]"
    }
   ]
  }
 ]
}