{
 "title": "Waku Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connected Peers #0",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "connected_peers{node=\"0\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #0",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"0\"}"
    }
   ]
  },
  {
   "title": "Dropped Envelopes #0",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"0\"} + dropped_from_future_envelopes_total{node=\"0\"} + dropped_low_pow_envelopes_total{node=\"0\"} + dropped_too_large_envelopes_total{node=\"0\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"0\"} + dropped_topic_mismatch_envelopes_total{node=\"0\"} +dropped_benign_duplicate_envelopes_total{node=\"0\"} + dropped_malicious_duplicate_envelopes_total{node=\"0\"}",
     "legendFormat": "dropped envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #0",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"0\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #0",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"0\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"0\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"0\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_malicious_duplicate_envelopes_total{node=\"0\"}",
     "legendFormat": "Malicious duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"0\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"0\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"0\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"0\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"0\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"0\"}",
     "legendFormat": "Too Large"
    }
   ]
  },
  {
   "title": "Waku Node #0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"0\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"0\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"0\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"0\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"0\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"0\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"0\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"0\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"0\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  }
 ]
}