# Nimbus
# Copyright (c) 2026 Status Research & Development GmbH
# Licensed under either of
#  * Apache License, version 2.0, ([LICENSE-APACHE](LICENSE-APACHE))
#  * MIT license ([LICENSE-MIT](LICENSE-MIT))
# at your option.
# This file may not be copied, modified, or distributed except according to
# those terms.

version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    ignore:
      - dependency-name: vendor/nim-libp2p
        versions: ["<= 0.0.0"]
      - dependency-name: vendor/nimbus-eth2
        versions: ["<= 0.0.0"]
    schedule:
      interval: daily
