{
 "title": "Nimbus Eth1",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(nec_sync_peers, instance)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(nec_sync_peers{instance=\"${instance}\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Syncing - Blocks left to sync",
   "type": "timeseries",
   "description": "Sync description",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "beacon_latest{instance=\"${instance}\",container=\"${container}\"} - beacon_head{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "beacon_latest"
    },
    {
     "expr": "nec_consensus_head{instance=\"${instance}\",container=\"${container}\"} - nec_execution_head{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "blocks"
    },
    {
     "expr": "clamp_min(nec_sync_consensus_head{instance=\"${instance}\",container=\"${container}\"} - nec_execution_head{instance=\"${instance}\",container=\"${container}\"},0)",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Sync Peers vs Block Lists",
   "type": "timeseries",
   "description": "Buddies description",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "beacon_buddies{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "beacon_buddies"
    },
    {
     "expr": "nec_sync_peers{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "nec_sync_peers"
    },
    {
     "expr": "nec_sync_block_lists_staged{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "nec_sync_block_lists_staged"
    },
    {
     "expr": "beacon_block_lists_staged{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "beacon_block_lists_staged"
    }
   ]
  },
  {
   "title": "Base vs Execution Head",
   "type": "timeseries",
   "description": "Sync description",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "beacon_latest{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "beacon_latest"
    },
    {
     "expr": "nec_execution_head{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "nec_execution_head"
    },
    {
     "expr": "nec_base{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "nec_base"
    },
    {
     "expr": "beacon_base{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "beacon_base"
    }
   ]
  },
  {
   "title": "Consensus Sync Head",
   "type": "timeseries",
   "description": "Sync description",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "nec_consensus_head{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "nec_consensus_head"
    },
    {
     "expr": "beacon_target{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "beacon_target"
    },
    {
     "expr": "nec_sync_consensus_head{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "nec_sync_consensus_head"
    }
   ]
  },
  { "title": "Import (Manual)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Imported Block",
   "type": "timeseries",
   "description": "Latest imported block number",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "nec_import_block_number{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "nec_import_block_number"
    }
   ]
  },
  {
   "title": "Transactions Processed",
   "type": "timeseries",
   "description": "Transactions processed during import",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "nec_imported_transactions_total{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "nec_imported_transactions_total"
    }
   ]
  },
  {
   "title": "Blocks Processed",
   "type": "timeseries",
   "description": "Blocks processed during import",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "nec_imported_blocks_total{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "nec_imported_blocks_total"
    }
   ]
  },
  {
   "title": "Gas Processed",
   "type": "timeseries",
   "description": "Gas processed during import",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "nec_imported_gas_total{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "nec_imported_gas_total"
    }
   ]
  },
  { "title": "RLPx (Networking)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "RLPX Connected Peers",
   "type": "timeseries",
   "description": "Number of connected peers in the pool",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rlpx_connected_peers{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "RLPX Failed Accept Attempts",
   "type": "timeseries",
   "description": "Number of rlpx accept attempts that failed",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (reason) (increase(rlpx_accept_failure_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RLPX Accepted Peers",
   "type": "timeseries",
   "description": "Number of successful rlpx accepted peers",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(rlpx_accept_success_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "increase(rlpx_accept_success_total)"
    }
   ]
  },
  {
   "title": "RLPX Failed Connection Attempts",
   "type": "timeseries",
   "description": "Number of rlpx connects that failed",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (reason) (increase(rlpx_connect_failure_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RLPX Successful Connections",
   "type": "timeseries",
   "description": "Number of successfull rlpx connects",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(rlpx_connect_success_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "increase(rlpx_connect_success_total)"
    }
   ]
  },
  { "title": "Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Discovery v4 routing table nodes",
   "type": "timeseries",
   "description": "Discovery v4 routing table nodes",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "discv4_routing_table_nodes{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "discv4_routing_table_nodes"
    }
   ]
  },
  {
   "title": "Discv5 message rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(discovery_message_requests_outgoing_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "discovery_message_requests_outgoing [{{response}}]"
    },
    {
     "expr": "rate(discovery_unsolicited_messages_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "unsolicited messages"
    }
   ]
  },
  {
   "title": "Discovery v5 routing table nodes",
   "type": "timeseries",
   "description": "Discovery v5 routing table nodes",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "routing_table_nodes{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  }
 ]
}