package example

/*
#cgo LDFLAGS: -L../../build/libverifproxy/ -lverifproxy
#include <stdlib.h>
#include <verifproxy.h>  // Replace with the actual header file generated by Nim
*/
import "C"
import (
	"fmt"
	"time"
)

//export myCallback
func myCallback(ctx *C.Context, status C.int, res *C.char) {
	// Handle the callback response from Nim
	fmt.Printf("Callback received! Status: %d, Response: %s\n", status, C.GoString(res))
}

func main() {
	// Initialize the Nim library
	C.NimMain()
	ctx := C.createAsyncTaskContext()

	// Example: Start verification proxy
	configJson := `{
		"eth2Network": "mainnet",
		"trustedBlockRoot": "0xd9e4f5b2e7a8e50f9348a1890114ae522d3771ddfb44d8b7e7e2978c21869e91",
		"backendUrl": "https://eth.blockrazor.xyz",
		"beaconApiUrls": "http://testing.mainnet.beacon-api.nimbus.team,http://www.lightclientdata.org",
		"logLevel": "FATAL",
		"logStdout": "None"

	}`

	C.CallBackProc(myCallback)

	// Start the verification proxy in a separate Go routine
	go func() {
		time.Sleep(50 * time.Millisecond)
		C.startVerifProxy(ctx, C.CString(configJson), myCallback)
	}()
	go func() {
		time.Sleep(5000 * time.Millisecond)
		C.eth_blockNumber(ctx, myCallback)
	}()
	// Main loop where you keep calling the poll function
	for {
		C.pollAsyncTaskEngine(nil)
		time.Sleep(100 * time.Millisecond) // Adjust the sleep duration based on your needs

	}
}
