/* Generated by Nim Compiler v1.6.12 */
#ifndef __verifproxy__
#define __verifproxy__
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct VerifProxyContext VerifProxyContext;
typedef void (*onHeaderCallback)(NCSTRING s, int t);
void quit(void);
VerifProxyContext* startLightClientProxy(NCSTRING configJson, onHeaderCallback onHeader);
#endif /* __verifproxy__ */
