{
 "title": "Fluffy Dashboard",
 "description": "Dashboard for Fluffy, a Portal network client",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval]) * 100"
    }
   ]
  },
  {
   "title": "RSS mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "ENR auto updates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discovery_enr_auto_update_total"
    }
   ]
  },
  {
   "title": "uTP established connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "utp_established_connections" }
   ]
  },
  {
   "title": "Portal message requests out / responses in",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(portal_message_requests_outgoing_total[$__rate_interval])"
    },
    {
     "expr": "rate(portal_message_response_incoming_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "CPU usage %"
    },
    { "expr": "process_open_fds", "legendFormat": "open file descriptors" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS" },
    { "expr": "sum(nim_gc_mem_bytes)", "legendFormat": "Nim GC mem total" },
    { "expr": "sum(nim_gc_mem_occupied_bytes)", "legendFormat": "Nim GC mem used" }
   ]
  },
  {
   "title": "Portal message requests in",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(portal_message_requests_incoming_total[$__rate_interval])"
    },
    {}
   ]
  },
  {
   "title": "GC heap objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "Content Requests per lookup",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_lookup_content_requests_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ENRs packed per Nodes msg",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_nodes_enrs_packed_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Discv5 session cache hit/miss ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(discovery_session_lru_cache_hits_total[$__rate_interval]) / (rate(discovery_session_lru_cache_hits_total[$__rate_interval]) + rate(discovery_session_lru_cache_misses_total[$__rate_interval]))",
     "legendFormat": "session cache hits / (hits + misses)"
    },
    {
     "expr": "rate(discovery_session_decrypt_failures_total[$__rate_interval])",
     "legendFormat": "session decrypt failures"
    }
   ]
  },
  {
   "title": "Content Keys Offered",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_content_keys_offered_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ENRs packed per Content msg",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_content_enrs_packed_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Discv5 message rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(discovery_message_requests_incoming_total[$__rate_interval])",
     "legendFormat": "discovery_message_requests_incoming [{{response}}]"
    },
    {
     "expr": "rate(discovery_message_requests_outgoing_total[$__rate_interval])",
     "legendFormat": "discovery_message_requests_outgoing [{{response}}]"
    },
    {
     "expr": "rate(discovery_unsolicited_messages_total[$__rate_interval])",
     "legendFormat": "unsolicited messages"
    }
   ]
  },
  {
   "title": "Content Keys Accepted",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_content_keys_accepted_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Routing table nodes - BUGGED: Metrics count over all routing tables together",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "routing_table_nodes" }
   ]
  },
  {
   "title": "Neighborhood gossip content offers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(portal_gossip_offers_successful_total[$__rate_interval])",
     "legendFormat": "portal_gossip_offers_successful[{{protocol_id}}]"
    },
    {
     "expr": "rate(portal_gossip_offers_failed_total[$__rate_interval])",
     "legendFormat": "portal_gossip_offers_failed[{{protocol_id}}]"
    }
   ]
  },
  {
   "title": "uTP incoming connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(utp_allowed_incoming_total[$__rate_interval])",
     "legendFormat": "utp_allowed_incoming"
    },
    {
     "expr": "rate(utp_declined_incoming_total[$__rate_interval])",
     "legendFormat": "utp_declined_incoming"
    }
   ]
  },
  {
   "title": "Portal message decoding failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "portal_message_decoding_failures_total"
    }
   ]
  },
  {
   "title": "uTP outgoing connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(utp_success_outgoing_total[$__rate_interval])",
     "legendFormat": "utp_success_outgoing"
    },
    {
     "expr": "rate(utp_failed_outgoing_total[$__rate_interval])",
     "legendFormat": "utp_failed_outgoing"
    }
   ]
  },
  {
   "title": "uTP Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(utp_failed_packets_total[$__rate_interval])",
     "legendFormat": "utp_failed_packets"
    },
    {
     "expr": "rate(utp_received_packets_total[$__rate_interval])",
     "legendFormat": "utp_received_packets"
    }
   ]
  },
  {
   "title": "uTP established connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "utp_established_connections" }
   ]
  }
 ]
}