# Nimbus
# Copyright (c) 2025-2026 Status Research & Development GmbH
# Licensed under either of
#  * Apache License, version 2.0, ([LICENSE-APACHE](LICENSE-APACHE))
#  * MIT license ([LICENSE-MIT](LICENSE-MIT))
# at your option.
# This file may not be copied, modified, or distributed except according to
# those terms.

{.push raises: [], gcsafe.}

import
  std/[sets, algorithm],
  eth/common/[block_access_lists, block_access_lists_rlp, hashes],
  stint,
  results,
  ../constants,
  ./block_access_list_utils

export block_access_lists, hashes, results

# The block access list is constrained by the block gas limit rather than a fixed
# maximum number of items. The constraint is defined as:
#
# bal_items <= block_gas_limit // ITEM_COST
#
# Where:
# - bal_items = addresses + storage_keys
# - ITEM_COST = 2000

const BAL_ITEM_COST = 2000.GasInt

func checkBalSize(
    bal: BlockAccessListRef, blockGasLimit: GasInt
): Result[void, string] =
  # We assume there are no duplicate addresses, storageChanges or storageReads
  # when doing this size check. If there are duplicates then the duplicated
  # values would simply increase the item count and fail the size check earlier.
  # This is fine because BALs with duplicates will get rejected in the other
  # validations anyway.

  let addressCount = bal[].len()

  var storageKeysCount = 0
  for changes in bal[]:
    storageKeysCount += changes.storageChanges.len() + changes.storageReads.len()

  let balItemCount = addressCount + storageKeysCount

  if balItemCount.GasInt <= blockGasLimit div BAL_ITEM_COST:
    ok()
  else:
    err("BAL exceeds max items cap")

func validate*(
    bal: BlockAccessListRef,
    expectedHash: Hash32,
    blockGasLimit: GasInt = DEFAULT_GAS_LIMIT,
): Result[void, string] =
  ## Validate that a block access list is structurally correct and matches the
  ## expected hash.

  # Check the size of the BAL to protect against DOS attacks. Do this first
  # because it is more efficient than the rest of the validations below.
  ?bal.checkBalSize(blockGasLimit)

  # The custom cmpTreatEqualAsGreater compare functions below enable validating
  # that each list contains no duplicates in each call to isSorted.

  # Validate addresses
  if not bal[].isSorted(accChangesCmpTreatEqualAsGreater):
    return err("Addresses should be unique and sorted lexicographically")

  # Validate fields for each account
  for accountChanges in bal[]:
    # Validate storage changes
    if not accountChanges.storageChanges.isSorted(slotChangesCmpTreatEqualAsGreater):
      return err("Storage changes slots should be unique and sorted lexicographically")

    # Check storage changes
    var changedSlots: HashSet[StorageKey]
    for slotChanges in accountChanges.storageChanges:
      changedSlots.incl(slotChanges.slot)
      if slotChanges.changes.len == 0:
        return err("Each slot in storage changes must have at least one change")
      if not slotChanges.changes.isSorted(balIndexCmpTreatEqualAsGreater):
        return err("Slot changes should be unique and sorted by blockAccessIndex")

    # Check that storage changes and reads don't overlap for the same slot.
    for slot in accountChanges.storageReads:
      if changedSlots.contains(slot):
        return err("A slot should not be in both changes and reads")

    # Validate storage reads
    if not accountChanges.storageReads.isSorted(storageKeyCmpTreatEqualAsGreater):
      return err("Storage reads should be unique and sorted lexicographically")

    # Check balance changes
    if not accountChanges.balanceChanges.isSorted(balIndexCmpTreatEqualAsGreater):
      return err("Balance changes should be unique and sorted by blockAccessIndex")

    # Check nonce changes
    if not accountChanges.nonceChanges.isSorted(balIndexCmpTreatEqualAsGreater):
      return err("Nonce changes should be unique and sorted by blockAccessIndex")

    # Check code changes
    if not accountChanges.codeChanges.isSorted(balIndexCmpTreatEqualAsGreater):
      return err("Code changes should be unique and sorted by blockAccessIndex")

  # Check that the block access list matches the expected hash.
  if bal[].computeBlockAccessListHash() != expectedHash:
    return err("Computed block access list hash does not match the expected hash")

  ok()

func verifyChangesAt[T: BalanceChange | NonceChange | CodeChange](
    partialChanges, suppliedChanges: openArray[T],
    balIndex: int,
    kind: static string,
): Result[void, string] =
  let si = suppliedChanges.findWriteAt(balIndex)

  if partialChanges.len() == 0:
    if si >= 0:
      return err("supplied BAL has a " & kind &
        " change not generated by the transaction")
  elif partialChanges.len() == 1:
    if partialChanges[0].blockAccessIndex.int != balIndex:
      return err("partial BAL has a " & kind & " change at an unexpected index")
    if si < 0:
      return err(kind & " change missing from supplied BAL")
    if suppliedChanges[si] != partialChanges[0]:
      return err(kind & " change value mismatch")
  else:
    return err("partial BAL should have at most one " & kind & " change")

  ok()

func verifyAccountChanges(
    pAcc, sAcc: AccountChanges, balIndex: int
): Result[void, string] =
  for slotChanges in pAcc.storageChanges:
    if slotChanges.changes.len() != 1 or
        slotChanges.changes[0].blockAccessIndex.int != balIndex:
      return err("partial BAL slot changes should have a single change at " &
        "the current block access index")

    let si = sAcc.storageChanges.findSlotChanges(slotChanges.slot)
    if si < 0:
      return err("storage write missing from supplied BAL")

    let ci = sAcc.storageChanges[si].changes.findWriteAt(balIndex)
    if ci < 0:
      return err("storage write missing from supplied BAL at the current " &
        "block access index")

    if sAcc.storageChanges[si].changes[ci].newValue !=
        slotChanges.changes[0].newValue:
      return err("storage write value mismatch")

  var suppliedWrites = 0
  for slotChanges in sAcc.storageChanges:
    if slotChanges.changes.findWriteAt(balIndex) >= 0:
      inc suppliedWrites
  if suppliedWrites != pAcc.storageChanges.len():
    return err("supplied BAL has storage writes not generated by the transaction")

  ?verifyChangesAt(pAcc.balanceChanges, sAcc.balanceChanges, balIndex, "balance")
  ?verifyChangesAt(pAcc.nonceChanges, sAcc.nonceChanges, balIndex, "nonce")
  ?verifyChangesAt(pAcc.codeChanges, sAcc.codeChanges, balIndex, "code")

  for slot in pAcc.storageReads:
    if sAcc.storageReads.findStorageRead(slot) < 0 and
        sAcc.storageChanges.findSlotChanges(slot) < 0:
      return err("storage read missing from supplied BAL")

  ok()

func hasWritesAt(acc: AccountChanges, balIndex: int): bool =
  if acc.balanceChanges.findWriteAt(balIndex) >= 0 or
      acc.nonceChanges.findWriteAt(balIndex) >= 0 or
      acc.codeChanges.findWriteAt(balIndex) >= 0:
    return true
  for slotChanges in acc.storageChanges:
    if slotChanges.changes.findWriteAt(balIndex) >= 0:
      return true
  false

func verifyPartialBlockAccessList*(
    partial: BlockAccessList,
    supplied: BlockAccessList,
    balIndex: int,
): Result[void, string] =
  var pi = 0
  for sAcc in supplied:
    if pi < partial.len():
      let c = cmp(partial[pi].address.data(), sAcc.address.data())
      if c < 0:
        return err("account touched by the transaction is missing from the " &
          "supplied BAL")
      elif c == 0:
        ?verifyAccountChanges(partial[pi], sAcc, balIndex)
        inc pi
        continue

    if sAcc.hasWritesAt(balIndex):
      return err("supplied BAL has writes for an account not touched by " &
        "the transaction")

  if pi < partial.len():
    return err("account touched by the transaction is missing from the " &
      "supplied BAL")

  ok()
