# Nimbus Fluffy book
# Copyright (c) 2023-2024 Status Research & Development GmbH
# Licensed and distributed under either of
#   * MIT license (license terms in the root directory or at https://opensource.org/licenses/MIT).
#   * Apache v2 license (license terms in the root directory or at https://www.apache.org/licenses/LICENSE-2.0).
# at your option. This file may not be copied, modified, or distributed except according to those terms.

site_name: The Nimbus Fluffy Guide
theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - content.tabs.link
  palette:
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode


extra_css:
  - stylesheets/extra.css

# Support urls previously used by mdbook
use_directory_urls: false
repo_url: https://github.com/status-im/nimbus-eth1
edit_uri: edit/master/fluffy/docs/the_fluffy_book/docs
docs_dir: docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      toc_depth: 3
      permalink: "#"

nav:
  - Home:
    - 'index.md'

  - Getting started:
    - 'quick-start.md'
    - 'quick-start-windows.md'
    - 'quick-start-docker.md'

  - How-to:
    - Installation:
      - 'prerequisites.md'
      - 'build-from-source.md'
      - 'upgrade.md'
      - 'metrics.md'
    - Access the network:
      - 'connect-to-portal.md'
      - 'access-content.md'
    - Portal bridge:
      - 'history-content-bridging.md'
      - 'beacon-content-bridging.md'
    - 'db_pruning.md'

  - Developers:
    - 'basics-for-developers.md'
    - 'test-suite.md'
    - 'adding-documentation.md'
    - Local testnet:
      - 'run-local-testnet.md'
      - 'testnet-history-network.md'
      - 'testnet-beacon-network.md'
    - 'fluffy-with-portal-hive.md'
    - 'protocol-interop-testing.md'
    - 'eth-data-exporter.md'
