name: Nimbus Nix CI
permissions:
  contents: read
  pull-requests: read
  checks: write
on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: '${{ matrix.system }} / ${{ matrix.nixpkg }}'
    timeout-minutes: 25
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        system:
          - aarch64-darwin
          - x86_64-linux
        nixpkg:
          - nimbus_execution_client
          - nimbus_verified_proxy

        include:
          - system: aarch64-darwin
            runs_on: [self-hosted, macOS, ARM64]

          - system: x86_64-linux
            runs_on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v5
        with:
          show-progress: false
          submodules: recursive
          lfs: false

      - name: 'Run Nix build for ${{ matrix.nixpkg }}'
        shell: bash
        run: nix build --fallback -L '.?submodules=1#${{ matrix.nixpkg }}'

      - name: 'Run NixOS service check for ${{ matrix.nixpkg }}'
        if: ${{ matrix.nixpkg == 'execution-client' }}
        run: nix run '.#checks.${{ matrix.system }}.${{ matrix.check }}.driver'

      - name: 'Show result contents'
        shell: bash
        run: find result/ -type f
